/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vending_machine;

import java.io.File;

public class App {

    public static void main(String[] args) {
        

        String resourcePath = null;
        switch(System.getProperty("os.name")) {
            case "Linux":
                resourcePath = "";
                break;
            default:
                resourcePath = "Documents/";
                break;
        }

        String filePath = String.format("/%s/%svending_machine", System.getProperty("user.home"), resourcePath);
        new File(filePath).mkdirs();

        Database db = new Database(filePath + "/vending.db");
        db.init();
        Model model = new Model(db);
        LandingPage landingPage = new LandingPage(model);
    }
}
